### ISSUE TITLE
issue running amuse-interface python scripts

### ISSUE THREAD

**Issue by marlito-gonaldo-byte** [lwang-astro/PeTar#51]
Hello, I am trying to run the amuse interface python scripts : test_interface.py and run_one_cluster_movie.py but it won't work, I have these errors : 
```
python3 test_interface.py
Initial
[edr20601.dip.tu-dresden.de:34683] shmem: mmap: an error occurred while determining whether or not /var/folders/69/q0sxjwg97jg1_jbm84qfy3vc0000gn/T//ompi.edr20601.501/jf.0/1586298880/sm_segment.edr20601.501.5e8d0000.0 could be created.
Traceback (most recent call last):
  File "/Users/maelgonin/Desktop/PBH/code/PeTar-master/amuse-interface/test_interface.py", line 14, in <module>
    gravity = petar(number_of_workers=2, redirection='none')
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/community/petar/interface.py", line 409, in __init__
    petarInterface(**keyword_arguments),
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/community/petar/interface.py", line 38, in __init__
    CodeInterface.__init__(
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/rfi/core.py", line 748, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/rfi/core.py", line 767, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/rfi/channel.py", line 916, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)
  File "/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/rfi/channel.py", line 720, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
amuse.support.exceptions.CodeException: The worker application does not exist, it should be at:
/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/_workers/petar_worker
/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/_workers/petar_worker
/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/community/petar/petar_worker
/Users/maelgonin/Desktop/PBH/code/amuse/src/amuse/rfi/petar_worker
```

and 
```
python3 run_one_cluster_movie.py
generate plummer model, N= 50
setting masses of the stars
particle type : <class 'amuse.datamodel.particles.Particle'>
cm type :  <class 'amuse.datamodel.particles.Particle'>
binaries type :  <class 'amuse.datamodel.particles.Particles'>
Traceback (most recent call last):
  File "/Users/maelgonin/Desktop/PBH/code/PeTar-master/amuse-interface/run_one_cluster_movie.py", line 358, in <module>
    particles, convert_nbody = generate_cluster(N, M |units.MSun, R)
  File "/Users/maelgonin/Desktop/PBH/code/PeTar-master/amuse-interface/run_one_cluster_movie.py", line 71, in generate_cluster
    particles[0].position = cm.position + binaries.position[0]
AttributeError: 'tuple' object has no attribute 'position'
```

I should mention that I did not installed PeTar from Amuse but by following the steps of the README. I installed Amuse separately, and could not install PeTar from Amuse, I have several installation problem with amuse. 
Also in `run_on_cluster_movie.py` I changed `new_binary_from_orbital_elements` for `generate_binaries function`, following this warning : `UserWarning: new_binary_from_orbital_elements is deprecated, use generate_binaries instead`

**Comment by marlito-gonaldo-byte** [comment]
I installed PeTar through AMUSE and I am now able to make the scripts work
